name: My Github Actions Workflow
on:
  push:  # Trigger on push events to any branch
    branches:
      - main  # You can specify the branch here; replace "main" if needed

jobs:
  testing_github:
    runs-on: ubuntu-latest
    steps:
      - name: Hello
        run: echo "Hello, Github Actions"
      - name: Display repo name
        run: echo "this workflow is running in ${{ github.repository }}"

